### ISSUE TITLE
how can I use grunt.filerev.summary?

### ISSUE THREAD

**Issue by jeroenhouben** [yeoman/grunt-filerev#6]
I'm trying to access that in a task that is run after revving. Like so:

```
"regex-replace": {
  build: { //specify a target with any name
    src: ['build/**/*.js'],
    actions: [
      {
          name: 'bar',
          search: 'app\/detailsController',
          replace: '<%= filerev.summary["js/app/detailsController"] %>',
          flags: 'g'
      }
    ]
  }
},
```

But that just gives me an "undefined" error. It looks like I cannot access the filerev.summary object. The revving works fine though, all files all revved as expected.

**Comment by RahulDole** [comment]
One way to access it is this:
    
    // Default task(s).
    grunt.registerTask('default', ['filerev', 'uglify', 'writeSummary']);

    grunt.registerTask('writeSummary', 'Writes the summary output of filerev task to a file', function() {
        grunt.file.write('filerevSummary.js', 'define([], function(){ return ' + JSON.stringify(grunt.filerev.summary) + '; })');
    })

In writeSummary task, I'm just writing the filerev summary object to a file so that I can use it later. I'm using requirejs, so I'm writing the file in AMD way. 
But strangely, if I try to access the summary object inside the uglify task (not mentioned here), then it gives me the same undefined error. That's what I'm trying to figure out currently.
